### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by Martin102000** [HCTools/hcdecryptor#1]
when i install it in termux android  or in Ubuntu, this apears
![Screenshot_20200823-171803_Termux](https://user-images.githubusercontent.com/9509040/90987863-9bb45b00-e564-11ea-945b-8c303097a66e.jpg)

**Comment by CONIGUERO** [comment]
> when i install it in termux android or in Ubuntu, this apears
> ![Screenshot_20200823-171803_Termux](https://user-images.githubusercontent.com/9509040/90987863-9bb45b00-e564-11ea-945b-8c303097a66e.jpg)

You need to do this:

    git clone https://github.com/HCTools/hcdecryptor.git
    cd hcdecryptor
    pip3 install -r requirements.txt
   
Then to decrypt an hc file:

    python3 decrypt.py file.hc

**Comment by Error404-code** [comment]
![Capture2](https://github.com/HCTools/hcdecryptor/assets/125489033/aa7df107-437f-4cd5-a590-ffafa89bfada)
